### ISSUE TITLE
Quit Button Color

### ISSUE THREAD

**Issue by mglodack** [dillonkearns/mobster#22]
It would be great if the `Quit` button was a different color like red.

**Comment by dillonkearns** [comment]
Thanks for the feedback! What do you think of this?

<img width="1437" alt="mobster_and_1__yarn_start__electron_helper__and_hot_keys_ _issue__21_ _dillonkearns_mobster" src="https://cloud.githubusercontent.com/assets/1384166/23581303/50de0756-00df-11e7-850d-1f1c2d40f442.png">

**Comment by mglodack** [comment]
https://media3.giphy.com/media/EaSH6bwyEQVkA/200_s.gif#0

**Comment by mglodack** [comment]
https://media3.giphy.com/media/EaSH6bwyEQVkA/200_s.gif#0

**Comment by mglodack** [comment]
That's nice! 👍

**Comment by mglodack** [comment]
Ship it!
