### ISSUE TITLE
Mobster crashes after clicking on "Start Mobbing"

### ISSUE THREAD

**Issue by steverb1** [dillonkearns/mobster#51]
We got the update today, and now the app crashes as soon as we click on "Start Mobbing".

**Comment by dillonkearns** [comment]
@steverb1 so sorry about that, I've pushed a fix. Please let me know if you encounter any other issues. Thank you for reporting this!

**Comment by steverb1** [comment]
We are still seeing the same behavior (crashing).  We are assuming that when we run it, it is automatically downloading the new version.  Is that true?

**Comment by dillonkearns** [comment]
Did you update to a new version? It takes around 60 seconds to show up, and
then you just click update. If that doesn't work you can always get it from
the releases tab in github, but that shouldn't be necessary.

**Comment by steverb1** [comment]
OK, I didn't realize I needed to wait a minute for the update.  We're all good now.  Thanks for the quick response!

**Comment by dillonkearns** [comment]
Fantastic, glad to hear it. And thank you for your responsiveness it's
super helpful!
