### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by britter** [dillonkearns/mobster#52]
I just wanted to say thank you for this awesome piece of software. It has changed the way we do pair and mob programming in my team. Thank you that you're investing your time to build this!

(Feel free to close this right away)

**Comment by dillonkearns** [comment]
That makes my day, thanks @britter! That's fantastic that your team is getting value from Mobster.

I'm curious, what are the things that have improved your team's experience of mobbing/pairing? And is there anything that would make the experience even better?

Cheers,

Dillon

**Comment by britter** [comment]
> I'm curious, what are the things that have improved your team's experience of mobbing/pairing?

Well to be honest, we weren't really doing pair programming. We always did it like two people sitting at a machine hacking together. Mobster helped us really to follow the process: It makes clear who is driver and who is navigator. It enforces time boxes. And it makes sure you take a break once in a while :-)

> And is there anything that would make the experience even better?

I realized, that we don't really pay attention to committing our code to SCM. So I wonder whether Mobster can help enforcing regular commits. The problem with this is, that sometime your timebox ends while you're in the middle of writing a test. This is probably something we have to pay more attention to, but I wonder whether there is something Mobster can do to help with this. For example run all the tests when the timebox ends and then blame the team if there is something failing. If everything is green it could just commit it. This may turn out to be complicated since mobster would have to know who to run tests...

**Comment by dillonkearns** [comment]
Wow, so great to hear that Mobster has helped with those things! So how did your team discover it then, was it recommended or searched for?

By the way, I'm not sure if you've looked at the tips in Mobster yet, but this article helped my pairing and mobbing tremendously: http://llewellynfalco.blogspot.com/2014/06/llewellyns-strong-style-pairing.html

**Comment by britter** [comment]
>  So how did your team discover it then, was it recommended or searched for?

Some guys at my company have used it and they recommended it. So we gave it a try :-)

> By the way, I'm not sure if you've looked at the tips in Mobster yet, but this article helped my pairing and mobbing tremendously: http://llewellynfalco.blogspot.com/2014/06/llewellyns-strong-style-pairing.html

Thank you, I'll definitely have a look!

**Comment by dillonkearns** [comment]
Neat, great to hear from you. Feel free to let me know if you have any suggestions in the future. And thanks for the feedback!
