### ISSUE TITLE
Infinitely forced to continue screen

### ISSUE THREAD

**Issue by roxworks** [dillonkearns/mobster#57]
Tried running from command line today, every time we hit continue it would just cycle people and return to the same screen.

**Comment by dillonkearns** [comment]
Hey @DanGiaime in development mode Mobster intentionally runs the timer for only 1 second. This is for faster iteration when experimenting. Check out [Timer/Main.elm lines 71-76](https://github.com/dillonkearns/mobster/blob/master/src/Timer/Main.elm#L71-L76).

I'm curious, are you running it from the command line to fix an issue, to make an improvement or a PR, or just to run the app? If you're just trying to run the app, the way to do that is by downloading it (there's an easy link at http://mobster.cc/).

**Comment by roxworks** [comment]
We wanted to take advantage of the mob-level commit script, so we figured we had to run from command line in order to use that. Is this not the case?

**Comment by dillonkearns** [comment]
Oh, I see, yeah you do not need to run it from the CLI to take advantage of that. The way it works is that Mobster will write out to that file every time the roster changes. The mob commit script simply reads that file (which is always up-to-date) and uses that to get the authors. Happy to help if you have any more questions setting it up! I'll close this issue out to avoid confusion for anyone browsing open issues though. Cheers!
