### ISSUE TITLE
Feature request: Update got credentials based on the current user

### ISSUE THREAD

**Issue by timgifford** [dillonkearns/mobster#61]
While using Mobster, it would be cool if it switched the git credential to the current user.

**Comment by dillonkearns** [comment]
Hello! Thanks for starting the discussion.

Take a look at this example script: https://github.com/dillonkearns/mobster/blob/master/mobster-commit.sh. Mobster makes the active mobsters available as a comma-separated list. The first one in the list is the current driver.

You could do a `case` statement on the name of the current driver. Then, based on that name, you could set `USER_EMAIL` in that script. And you could even change out the ssh key or something like that if you needed to. Why don't you start with giving that a try and seeing how it goes.

I don't think it would make sense to couple Mobster to git or running CLI commands to change the driver. Instead, I like the approach of providing simple ways for users to build scripts using that information. Let me know how that works for your team and give me your feedback 👍Thank you!

**Comment by timgifford** [comment]
I like it! Thanks for the quick response.

**Comment by dillonkearns** [comment]
Great, glad that solves your problem! 👍
