### ISSUE TITLE
Add remote working possibilities

### ISSUE THREAD

**Issue by dev-in-disguise** [dillonkearns/mobster#77]
My team and I are working in a remote environment. Therefore it only makes sense to have the mobster application running on only one of our team members device which I see as pretty bad. The whole mob now has a dependency on this one person which runs the mobster application to make sure the rotations are held in place.

For our team setup I have two possible solutions in mind that would be good:

1. Create a web version of the mobster app where you can login and see your personal mobbing session with your team
2. Since we are using Slack an integration of the mobster app in there would be also quite nice

Would you plan to do any of those things?

**Comment by dillonkearns** [comment]
A VS Code or other editor plugin would be a good way to approach it, too. There's one here that I haven't tried, but looks interesting: https://marketplace.visualstudio.com/items?itemName=pluralsight.live-share-mob-timer.

I'm not planning on working on a remote syncing version, but I agree that it would be very useful!

**Comment by dev-in-disguise** [comment]
Oh, that's a nice way to do it as well! Unfortunately a team member of ours uses Rider as an IDE so that's not really usable for us. 
Thanks anyway for your reply Dillon!

**Comment by absynce** [comment]
Folks across our team use different tools in their day-to-day. But, when mobbing, we all use [Zed](https://zed.dev/docs/channels) channels for collaboration—super fast and simple enough. One person runs Mobster and shares their screen, as well as any non-IDE stuff, such as the app running in the browser. 

Sorry for being a zombie, but I wanted to give an updated answer for 2025. 🧟

It still relies on one person running Mobster, but it works fine for us.
